<a href="https://colab.research.google.com/github/dimasnurmiraj/221230053-Pengantar-ML/blob/main/week_2/latihan_praktikum_4_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

# ==================================================
# Simulasi batch data (32 sampel, 10 fitur)
# ==================================================
batch_size, n_features = 32, 10
torch.manual_seed(123)  # seed agar hasil reproducible
X = torch.randn(batch_size, n_features)
W = torch.randn(n_features, 1)
b = torch.randn(1)

# ==================================================
# Linear layer (y = XW + b)
# ==================================================
def linear_layer(x, w, bias):
    return x @ w + bias

y_linear = linear_layer(X, W, b)

# ==================================================
# ReLU Activation
# ==================================================
def relu(x):
    return torch.clamp(x, min=0.0)  # lebih ringkas pakai clamp

y_relu = relu(y_linear)

# ==================================================
# Batch Normalization sederhana
# ==================================================
def batch_norm(x, eps=1e-5):
    mean = x.mean(dim=0, keepdim=True)
    std = x.std(dim=0, unbiased=False, keepdim=True)  # pakai unbiased=False biar stabil
    return (x - mean) / (std + eps)

y_bn = batch_norm(X)

# ==================================================
# One-hot Encoding
# ==================================================
def one_hot_encoding(labels, num_classes):
    oh = torch.zeros(labels.size(0), num_classes)
    oh[torch.arange(labels.size(0)), labels] = 1
    return oh

labels = torch.randint(0, 4, (8,))  # modifikasi: kelas jadi 4, label 8 sampel
y_onehot = one_hot_encoding(labels, num_classes=4)

# ==================================================
# Manual Matrix Multiplication
# ==================================================
def manual_matmul(A, B):
    m, n = A.shape
    n2, p = B.shape
    assert n == n2, "Inner dimensions must match"
    C = torch.zeros(m, p)
    for i in range(m):
        for j in range(p):
            C[i, j] = torch.sum(A[i, :] * B[:, j])  # lebih ringkas
    return C

# Uji coba
A = torch.tensor([[2., 0.], [1., -1.]], dtype=torch.float32)
B = torch.tensor([[3., 1.], [0., 2.]], dtype=torch.float32)
manual_res = manual_matmul(A, B)
torch_res = A @ B

# ==================================================
# OUTPUT
# ==================================================
print("=== LINEAR LAYER OUTPUT (first 5 rows) ===\n", y_linear[:5])
print("\n=== RELU ACTIVATION (first 5 rows) ===\n", y_relu[:5])
print("\n=== BATCH NORMALIZATION (first 5 rows) ===\n", y_bn[:5])
print("\n=== LABELS ===\n", labels)
print("\n=== ONE-HOT ENCODING ===\n", y_onehot)

print("\n=== MATRIX MULTIPLICATION TEST ===")
print("Manual result:\n", manual_res)
print("Torch result:\n", torch_res)

# ==================================================
# Assertions
# ==================================================
assert y_linear.shape == (batch_size, 1), "Linear output salah"
assert torch.all(y_relu >= 0), "ReLU salah (ada nilai negatif)"
assert y_bn.shape == X.shape, "Batch norm shape salah"
assert y_onehot.shape == (8, 4), "One-hot shape salah"
assert torch.allclose(manual_res, torch_res), "Matrix multiplication salah"

print("\n✅ Semua test lulus tanpa error!")


=== LINEAR LAYER OUTPUT (first 5 rows) ===
 tensor([[-2.0634],
        [-2.0481],
        [-8.9384],
        [ 4.7898],
        [-4.7585]])

=== RELU ACTIVATION (first 5 rows) ===
 tensor([[0.0000],
        [0.0000],
        [0.0000],
        [4.7898],
        [0.0000]])

=== BATCH NORMALIZATION (first 5 rows) ===
 tensor([[ 0.1607, -0.0610, -0.2393, -0.8636,  0.1858,  0.5207, -0.0631, -0.1313,
          1.6012, -0.7617],
        [ 0.5567, -1.1333,  0.2830,  2.0541,  0.3319,  0.1168,  0.0771, -0.8561,
          0.4582,  1.1926],
        [ 1.5247,  1.2261,  1.4682, -0.4088,  0.3330, -1.7847,  1.1030, -1.0003,
         -0.7506,  0.6441],
        [-0.9019, -2.3782, -1.3440,  0.0370, -2.2845,  0.9254, -0.2291, -0.7587,
          0.0550, -0.6637],
        [ 0.7565,  1.4464,  0.7666, -0.3789, -0.0633, -0.2577,  0.4145, -0.3639,
          1.7352,  1.8449]])

=== LABELS ===
 tensor([0, 0, 3, 3, 1, 3, 3, 0])

=== ONE-HOT ENCODING ===
 tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        